<?php

declare(strict_types=1);

use Lock\Server\Audit\Sinks\LogAuditSink;
use Lock\Server\Credentials\RecoveryCodeProvider;
use Lock\Server\Credentials\TotpFactorProvider;
use Lock\Server\Credentials\WebAuthnFactorProvider;
use Lock\Server\SigningKeys\DatabaseSigningKeyStore;

// Two kinds of values live here. A key is per-realm exactly when a Realm
// settings object reads it — ConfiguredRealm supplies the defaults below, and
// an application with a realm model overrides them per realm through the Realm
// contract. Everything else is deployment-wide, including `auth`, the key
// store, `session.token.guard`, the audit sink, `routes` and `install_self`.
return [
    // Identifier of the realm requests belong to outside a matched route —
    // console commands, queued jobs — and of the only realm in a single-realm
    // deployment. Bind a RealmRepository to serve realms from your own model.
    'realm' => env('OIDC_REALM', 'default'),

    // The origin the provider is served from, without a path: routes live at
    // the application root, so an issuer like https://example.com/idp would
    // name URLs that do not exist. Serve the provider from its own host or
    // subdomain instead. In `domain` routing each realm's own host is the
    // origin and this value supplies only the scheme.
    'issuer' => env('OIDC_ISSUER'),

    /*
    |--------------------------------------------------------------------------
    | Signing keys
    |--------------------------------------------------------------------------
    |
    | Tokens are signed with RS256. `store` is a class-string of a
    | SigningKeyStore implementation resolved from the container; the shipped
    | DatabaseSigningKeyStore keeps the keypair in `oidc_signing_keys` with the
    | private key encrypted at rest and retires the previous key on rotation so
    | tokens it signed keep verifying. Generate the first key with
    | `oidc:rotate-keys --if-missing`. Bind your own SigningKeyStore for a KMS
    | or a vault.
    |
    */
    'keys' => [
        'store' => DatabaseSigningKeyStore::class,

        // RSA modulus length of keys generated by oidc:rotate-keys.
        'size' => (int) env('OIDC_KEY_SIZE', 2048),
    ],

    // Token lifetimes in seconds.
    'tokens' => [
        // Interactive access token (authorization_code) + refreshed access tokens. Short, per industry.
        'access_token' => (int) env('OIDC_ACCESS_TOKEN_TTL', 900),
        'id_token' => (int) env('OIDC_ID_TOKEN_TTL', 3600),
        // Machine-to-machine (client_credentials): no refresh, no session; client re-requests. Own TTL.
        'client_credentials' => (int) env('OIDC_M2M_ACCESS_TOKEN_TTL', 3600),
        // Idle cap on an interactive session: a refresh token unused for this long is dead.
        // The absolute cap is oidc.session.absolute_lifetime and always wins.
        'refresh_token' => (int) env('OIDC_REFRESH_TOKEN_TTL', 1209600),
        // How long a password reset link stays valid.
        'password_reset' => (int) env('OIDC_PASSWORD_RESET_TTL', 3600),
    ],

    // Retention starts after expiry/revocation for tokens and after every
    // back-channel recipient reaches a terminal outcome for sessions.
    'pruning' => [
        'tokens' => (int) env('OIDC_PRUNING_TOKENS', 604800),
        'sessions' => (int) env('OIDC_PRUNING_SESSIONS', 86400),
    ],

    'session' => [
        'cookie_name' => env('OIDC_SESSION_COOKIE'),
        'logout_retry_lifetime' => (int) env('OIDC_LOGOUT_RETRY_LIFETIME', 86400),

        // Absolute cap on an interactive session, from login. Refresh is denied past this and the user
        // must re-authenticate; refresh-token rotation cannot extend it. Drives context.expires_at,
        // the refresh deny-check, and context pruning. The idle cap is tokens.refresh_token.
        'absolute_lifetime' => (int) env('OIDC_SESSION_ABSOLUTE_LIFETIME', 2592000),

        // The first-party session root token minted on login for browser-fetch.
        'token' => [
            'ttl' => (int) env('OIDC_SESSION_TOKEN_TTL', 3600),
            'refresh_skew' => 60,
            'scopes' => null,
            // Guard whose login/logout owns the session token. Null falls back to
            // the OIDC auth guard (oidc.auth.guard), then the application's default
            // guard; other guards never mint or revoke.
            'guard' => env('OIDC_SESSION_TOKEN_GUARD'),
        ],
    ],

    // API scope catalog consulted by the scope repository at enumeration time
    // (consent, discovery, issuance): an inline [scope => description] map, or
    // the class-string of a ScopeCatalog implementation resolved from the
    // container. Every scope belongs to one resource: an entry listed under a
    // resource in `resources` below is requestable only when that resource is,
    // the rest belong to the realm itself and are requestable only without a
    // `resource` (or with the issuer URL). A catalog class is asked for the
    // resources of the request instead and owns that split itself. Its scopes()
    // may hit the database — failures fall back to an empty catalog so key- and
    // db-less artisan runs never break; an invalid class-string fails loudly at
    // first enumeration.
    'scopes' => [],

    'claims_supported' => [
        'iss', 'sub', 'aud', 'exp', 'iat', 'auth_time', 'nonce', 'at_hash', 'azp', 'acr', 'amr', 'sid',
        'name', 'email', 'email_verified', 'locale', 'zoneinfo', 'updated_at',
    ],

    /*
    |--------------------------------------------------------------------------
    | Clients
    |--------------------------------------------------------------------------
    |
    | `first_party` names the confidential client this application uses for
    | itself: it mints the session root token and, with `trusted`, skips the
    | consent screen. `oidc:install-self` provisions it from `install_self`
    | below. `trusted` lists further client ids that skip consent.
    |
    | `registration` is RFC 7591 dynamic client registration. When enabled,
    | `POST /oauth/register` lets clients (e.g. MCP clients such as Claude or
    | Cursor) register themselves without credentials. A client registering
    | `token_endpoint_auth_method` `none` (the default) is public; one
    | registering `client_secret_basic` or `client_secret_post` is confidential
    | and receives its secret once, on the registration response. PKCE is
    | enforced for every client either way. Redirect URIs must use
    | http(s) — hosts checked against `allowed_redirect_domains` ('*' allows
    | any) — or one of the `allowed_redirect_schemes` (e.g. 'claude', 'cursor',
    | 'vscode'; a non-http scheme requires a host). Registered clients get
    | the realm's scope assignment like every other client.
    |
    | `default_scopes` and `optional_scopes` are assigned to every client the
    | realm creates (ClientRepository, `oidc:client`, dynamic registration).
    | Default scopes are granted without being requested, optional scopes on
    | request; a scope outside the assignment is `invalid_scope`. `*` among
    | the optional scopes stands for every scope the requested resources own.
    | An entry may name the resource that owns the scope
    | ('https://api.internal/orders orders:read'), which limits it to requests
    | for that resource; a bare entry holds under every resource.
    |
    | `token_exchange` enables the RFC 8693 grant.
    |
    */
    'clients' => [
        'first_party' => [
            'client_id' => env('OIDC_FIRST_PARTY_CLIENT') ?: null,
            'trusted' => env('OIDC_FIRST_PARTY_TRUSTED', false),
        ],

        'trusted' => [],

        'default_scopes' => [],
        'optional_scopes' => ['*'],

        'registration' => [
            'enabled' => env('OIDC_DCR_ENABLED', false),
            'allowed_redirect_schemes' => [],
            'allowed_redirect_domains' => ['*'],
        ],

        'token_exchange' => env('OIDC_TOKEN_EXCHANGE_ENABLED', true),
    ],

    /*
    |--------------------------------------------------------------------------
    | Self-SSO installation
    |--------------------------------------------------------------------------
    |
    | Input to the one-shot `oidc:install-self` command, which provisions the
    | first-party client named by `clients.first_party.client_id` and writes
    | the resulting credentials to the environment file. These lists are added
    | on top of the APP_URL-derived defaults; token exchange is enabled on the
    | client only when at least one audience is listed. Nothing here is read at
    | runtime — the provisioned client carries the values from then on.
    |
    */
    'install_self' => [
        'redirect_uris' => [],
        'post_logout_redirect_uris' => [],
        'allowed_exchange_audiences' => [],
    ],

    /*
    |--------------------------------------------------------------------------
    | Audit logging
    |--------------------------------------------------------------------------
    |
    | Every security-relevant event (logins, MFA, consent, token issuance,
    | revocation, client administration) is dispatched as an AuditEvent and
    | forwarded to the configured sink. `sink` is a class-string of an
    | AuditSink implementation resolved from the container; the shipped
    | LogAuditSink writes structured log lines (failures as warning, successes
    | as info) to `log_channel`, null meaning the default channel. Recording
    | is fail-open: sink failures are reported, never propagated.
    |
    */
    'audit' => [
        'enabled' => env('OIDC_AUDIT_ENABLED', true),
        'sink' => LogAuditSink::class,
        'log_channel' => env('OIDC_AUDIT_LOG_CHANNEL'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Resource servers (RFC 8707, RFC 9068, RFC 9728)
    |--------------------------------------------------------------------------
    |
    | The realm itself, identified by its issuer URL, is the default audience
    | of every access token minted without an RFC 8707 `resource`. Resource
    | servers listed here are further audiences a client may request through
    | `resource` (authorization code, client credentials) or `audience` (token
    | exchange), and the oidc guard accepts a bearer token addressed to any of
    | them; pair the route with CheckAudience to demand a specific one.
    |
    | The scopes a resource lists are the scopes it owns: they are requestable
    | only when the resource is, and the same value under two resources is two
    | different scopes. A scope no resource lists belongs to the realm itself.
    | A key that is a path relative to the issuer is identified as
    | `<issuer>/<path>` and advertised through RFC 9728 metadata at
    | `/.well-known/oauth-protected-resource/<path>`, where MCP clients resolve
    | their authorization server; an absolute URI names an external resource
    | server that validates tokens itself.
    |
    | 'mcp' => ['scopes' => ['mcp:use']],
    | 'https://api.internal/orders' => [],
    |
    */
    'resources' => [],

    // Read only while migrating. The package's `user_id` and `realm`
    // columns point at tables the application owns, so where they point — and
    // whether a foreign key is written at all — is configured rather than
    // assumed. A null table leaves the columns unconstrained.
    'migrations' => [
        'users' => [
            'table' => env('OIDC_MIGRATIONS_USERS_TABLE', 'users'),
            'column' => env('OIDC_MIGRATIONS_USERS_COLUMN', 'id'),
        ],
        // Off by default: a realm is an opaque identifier the application
        // owns, and there need not be a table behind it.
        'realms' => [
            'table' => env('OIDC_MIGRATIONS_REALMS_TABLE'),
            'column' => env('OIDC_MIGRATIONS_REALMS_COLUMN', 'slug'),
        ],
    ],

    // The guards the package authenticates against. Deployment-wide: a realm
    // cannot override them.
    'auth' => [
        'guard' => env('OIDC_AUTH_GUARD', 'identity'),
        'provider' => env('OIDC_AUTH_PROVIDER', 'users'),
        // Guard the userinfo endpoint and resource-server routes authenticate
        // bearer tokens against. Registered with the package's driver if absent.
        'api_guard' => env('OIDC_API_GUARD', 'oidc'),
    ],

    // Where the interactive login lives and what an authentication reports.
    'login' => [
        'username' => env('OIDC_AUTH_USERNAME', 'email'),
        // Route name or path the authorize endpoint sends anonymous users to.
        'route' => env('OIDC_LOGIN_ROUTE', 'identity.login'),
        'home' => env('OIDC_AUTH_HOME', '/dashboard'),
        // Where end-session lands without a post_logout_redirect_uri.
        'logout_redirect' => '/',
        // The `acr` claim (OIDC Core §2) an authentication earns: one method in
        // `amr` reports the single-factor value, two or more the multi-factor
        // one. Substitute URIs or RFC 6711 names your relying parties expect;
        // both are advertised as acr_values_supported.
        'acr_single_factor' => '1',
        'acr_multi_factor' => '2',
    ],

    // What the realm demands before it hands out a session.
    'authentication' => [
        // The interactive login methods this realm accepts. Registration and
        // password reset hang off `password`: both end in a password the realm
        // would not otherwise accept. A method that is not listed is refused
        // server-side, not merely hidden.
        'methods' => ['password', 'passkey', 'social'],
        // How hard the realm insists on a second factor: `never`, `if_enrolled`
        // (challenge whatever the user has enrolled) or `always` (a user without
        // a factor is sent to enrollment before the login completes).
        'mfa' => env('OIDC_AUTH_MFA', 'if_enrolled'),
        // Whether an unconfirmed email address blocks the login. With this on
        // the user gets no session at all until the address is verified.
        'email_verification_required' => env('OIDC_AUTH_EMAIL_VERIFICATION_REQUIRED', false),
    ],

    // The second factors a user can enroll and be challenged with.
    'credentials' => [
        'factors' => [
            TotpFactorProvider::class,
            RecoveryCodeProvider::class,
            WebAuthnFactorProvider::class,
        ],
        'challenge_providers' => ['totp', 'webauthn'],
        'totp_secret_length' => 16,
        'totp_window' => 1,
        'recovery_codes' => 8,
    ],

    // What a new password must satisfy, checked at registration and reset before
    // the app's CreateUser / ResetUserPassword action runs. `history` counts
    // previous passwords (the current one included) a new password may not
    // repeat; `max_age_days` marks a password as expired after that many days,
    // which raises the `update_password` required action and holds the login
    // until the user picks a new one.
    'password_policy' => [
        'min_length' => 8,
        'mixed_case' => false,
        'numbers' => false,
        'symbols' => false,
        'uncompromised' => false,
        'history' => 0,
        'max_age_days' => null,
    ],

    /*
    |--------------------------------------------------------------------------
    | Social login
    |--------------------------------------------------------------------------
    |
    | Upstream identity providers users can authenticate with. A provider is
    | active only when its client_id is configured. `driver` selects the
    | implementation: google, apple, github, or the generic `oidc` driver for
    | any OIDC-compliant IdP (requires `issuer`). Register custom drivers with
    | app(SocialProviderRegistry::class)->extend($driver, $creator).
    |
    */
    'social' => [
        // Attach an upstream identity to an existing local user when the
        // provider reports a verified email that matches.
        'link_by_verified_email' => true,
        // Create a local user on first social login through the bound
        // Brokering\Contracts\CreateUserFromSocialAccount action. Without a
        // binding, provisioning is effectively disabled.
        'auto_provision' => true,
        'providers' => [
            'google' => [
                'driver' => 'google',
                'client_id' => env('OIDC_SOCIAL_GOOGLE_CLIENT_ID'),
                'client_secret' => env('OIDC_SOCIAL_GOOGLE_CLIENT_SECRET'),
            ],
            'apple' => [
                'driver' => 'apple',
                'client_id' => env('OIDC_SOCIAL_APPLE_CLIENT_ID'),
                'team_id' => env('OIDC_SOCIAL_APPLE_TEAM_ID'),
                'key_id' => env('OIDC_SOCIAL_APPLE_KEY_ID'),
                'private_key' => env('OIDC_SOCIAL_APPLE_PRIVATE_KEY'),
            ],
            'github' => [
                'driver' => 'github',
                'client_id' => env('OIDC_SOCIAL_GITHUB_CLIENT_ID'),
                'client_secret' => env('OIDC_SOCIAL_GITHUB_CLIENT_SECRET'),
            ],
        ],
    ],

    'routes' => [
        'middleware' => [],

        // Middleware for the interactive screens only — login, registration,
        // password, verification, two-factor and consent. `middleware` above
        // also covers the protocol endpoints, which no browser session backs.
        'screen_middleware' => [],

        // `single` serves the configured realm from the application root, so the
        // issuer is the bare origin and provider and application share one
        // session. `path` serves every realm below /realms/{realm} with its own
        // issuer and its own session cookie. `domain` serves every realm from
        // its own host, so each is its own origin and every endpoint keeps the
        // path it has in `single`.
        'realms' => env('OIDC_ROUTE_REALMS', 'single'),

        // `domain` routing only: the host each realm is served from, mapped to
        // its identifier. An application with a realm model binds its own
        // RealmRepository and resolves the host from its own column instead.
        // The host comes from the request, so configure Laravel's trusted hosts.
        'domains' => [],
    ],
];
